config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :consultations
  draw :madmin
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/consultation.rb
class Consultation < ApplicationRecord
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  before_action :set_consultation, only: %i[ show edit update destroy ]

  # GET /consultations or /consultations.json
  def index
    @consultations = Consultation.all
  end

  # GET /consultations/1 or /consultations/1.json
  def show
  end

  # GET /consultations/new
  def new
    @consultation = Consultation.new
  end

  # GET /consultations/1/edit
  def edit
  end

  # POST /consultations or /consultations.json
  def create
    @consultation = Consultation.new(consultation_params)

    respond_to do |format|
      if @consultation.save
        format.html { redirect_to consultation_url(@consultation), notice: "Consultation was successfully created." }
        format.json { render :show, status: :created, location: @consultation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultations/1 or /consultations/1.json
  def update
    respond_to do |format|
      if @consultation.update(consultation_params)
        format.html { redirect_to consultation_url(@consultation), notice: "Consultation was successfully updated." }
        format.json { render :show, status: :ok, location: @consultation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultations/1 or /consultations/1.json
  def destroy
    @consultation.destroy

    respond_to do |format|
      format.html { redirect_to consultations_url, notice: "Consultation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultation
      @consultation = Consultation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consultation_params
      params.require(:consultation).permit(:title, :description, :start_time, :end_time)
    end
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/_consultation.html.erb
<div id="<%= dom_id consultation %>">
  <p>
    <strong>Title:</strong>
    <%= consultation.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= consultation.description %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= consultation.start_time %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= consultation.end_time %>
  </p>

</div>

app/views/consultations/_form.html.erb
<%= form_with(model: consultation) do |form| %>
  <% if consultation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consultation.errors.count, "error") %> prohibited this consultation from being saved:</h2>

      <ul>
      <% consultation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :start_time, class: 'form-label' %>
      <%= form.datetime_field :start_time, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :end_time, class: 'form-label' %>
      <%= form.datetime_field :end_time, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <% if consultation.persisted? %>
      <div class="float-end">
        <%= link_to 'Destroy', consultation, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>

    <%= form.submit class: 'btn btn-dark' %>

    <% if consultation.persisted? %>
      <%= link_to "Cancel", consultation, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", consultations_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/consultations/edit.html.erb
<h1>Edit Consultation</h1>

<%= render 'form', consultation: @consultation %>

app/views/consultations/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Consultations</h1>
  </div>

  <div class="col-sm-6 text-end">
  <%= link_to new_consultation_path, class: 'btn btn-warning' do %>
    Add New Consultation
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Title</th>
            <th>Description</th>
            <th>Start time</th>
            <th>End time</th>
            
          <th></th>
        
      </tr>
    </thead>

    <tbody>
      <% @consultations.each do |consultation| %>
        <%= content_tag :tr, id: dom_id(consultation), class: dom_class(consultation) do %>
          

                      <td><%= consultation.title %></td>
                      <td><%= consultation.description %></td>
                      <td><%= consultation.start_time %></td>
                      <td><%= consultation.end_time %></td>
          
          
            <td><%= link_to 'Show', consultation %></td>
          
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/consultations/new.html.erb
<div class="container">
<h1>New consultation</h1>

<%= render 'form', consultation: @consultation %> 
</div>

app/views/consultations/show.html.erb
<div class="page-header">
  <%= link_to consultations_path, class: 'btn btn-warning' do %>
    All Consultations
  <% end %>
  <%= link_to edit_consultation_path(@consultation), class: 'btn btn-dark' do %>
    Edit
  <% end %>
  <h1 class="mt-3">Consultation</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @consultation.title %></dd>
  <dt>Description:</dt>
  <dd><%= @consultation.description %></dd>
  <dt>Start time:</dt>
  <dd><%= @consultation.start_time %></dd>
  <dt>End time:</dt>
  <dd><%= @consultation.end_time %></dd>
</dl>